### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by jahvi** [jahvi/generator-htmlemail#1]
- [x] Prefix domain with http:// automatically if needed
- [x] Run tasks concurrently when possible
- [x] Support for adding multiple email targets
- [x] Support to change transport type
- [x] Allow users to change the initial template
- [x] Include SCSS support optionally
- [x] Add EJS support
